//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipecom.FactElec.Pymes.Agentes.Framework.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Direcciones {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Direcciones() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sipecom.FactElec.Pymes.Agentes.Framework.Recursos.Direcciones", typeof(Direcciones).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ServicioAdministracion.asmx.
        /// </summary>
        internal static string url_AdministracionAgente {
            get {
                return ResourceManager.GetString("url_AdministracionAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ServicioCliente.asmx.
        /// </summary>
        internal static string url_ClienteAgente {
            get {
                return ResourceManager.GetString("url_ClienteAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ServicioParticipante.asmx.
        /// </summary>
        internal static string url_ParticipanteAgente {
            get {
                return ResourceManager.GetString("url_ParticipanteAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ServicioSeguridad.asmx.
        /// </summary>
        internal static string url_SeguridadAgente {
            get {
                return ResourceManager.GetString("url_SeguridadAgente", resourceCulture);
            }
        }
    }
}
