//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sipecom.FactElec.Pymes.Agentes.Framework.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sipecom.FactElec.Pymes.Agentes.Framework.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de comunicacion al obtener usuario.
        /// </summary>
        internal static string exc_ObtPartCommunication {
            get {
                return ResourceManager.GetString("exc_ObtPartCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error general al obtener usuario.
        /// </summary>
        internal static string exc_ObtPartGeneral {
            get {
                return ResourceManager.GetString("exc_ObtPartGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de tiempo de espera al obtener usuario.
        /// </summary>
        internal static string exc_ObtPartTimeout {
            get {
                return ResourceManager.GetString("exc_ObtPartTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de comunicacion al registrar aplicacion.
        /// </summary>
        internal static string exc_RegAppCommunication {
            get {
                return ResourceManager.GetString("exc_RegAppCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error general al registrar aplicacion.
        /// </summary>
        internal static string exc_RegAppGeneral {
            get {
                return ResourceManager.GetString("exc_RegAppGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de tiempo de espera al registrar aplicacion.
        /// </summary>
        internal static string exc_RegAppTimeout {
            get {
                return ResourceManager.GetString("exc_RegAppTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de comunicacion al registrar usuario.
        /// </summary>
        internal static string exc_RegUsuCommunication {
            get {
                return ResourceManager.GetString("exc_RegUsuCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error general al registrar usuario.
        /// </summary>
        internal static string exc_RegUsuGeneral {
            get {
                return ResourceManager.GetString("exc_RegUsuGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de tiempo de espera al registrar usuario.
        /// </summary>
        internal static string exc_RegUsuTimeout {
            get {
                return ResourceManager.GetString("exc_RegUsuTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de comunicacion al resetear clave.
        /// </summary>
        internal static string exc_ResClaveCommunication {
            get {
                return ResourceManager.GetString("exc_ResClaveCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error general al resetear clave.
        /// </summary>
        internal static string exc_ResClaveGeneral {
            get {
                return ResourceManager.GetString("exc_ResClaveGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de tiempo de espera al resetear clave.
        /// </summary>
        internal static string exc_ResClaveTimeout {
            get {
                return ResourceManager.GetString("exc_ResClaveTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de clave exitoso.
        /// </summary>
        internal static string inf_CambioClave {
            get {
                return ResourceManager.GetString("inf_CambioClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        internal static string inf_Ok {
            get {
                return ResourceManager.GetString("inf_Ok", resourceCulture);
            }
        }
    }
}
