//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.Transversal.eComp.PDF.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContratoInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContratoInfo() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infraestructura.Transversal.eComp.PDF.Recursos.ContratoInfo", typeof(ContratoInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente podrá realizar cambios del plan elegido, ya sea este de mayor o menor valor, en el tiempo de duración del contrato (12 meses) De requerirlo, el cambio debe ser notificado con.
        /// </summary>
        internal static string Ctrt13TextoDos {
            get {
                return ResourceManager.GetString("Ctrt13TextoDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para modificar los términos y condiciones del presente contrato, sólo se realizará si ambas partes llegaran a un acuerdo, acerca de la modificación, cumpliendo de esta forma el principio de equidad. Ambas partes, leído el presente contrato lo firman y ratifican su contenido, comprometiéndose a su cumplimiento y para que así conste, se firman dos ejemplares de un mismo tenor e igual valor y efectos legales..
        /// </summary>
        internal static string Ctrt15TextoDos {
            get {
                return ResourceManager.GetString("Ctrt15TextoDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a con domicilio legal en {0}, en la ciudad de {1} Provincia del {2}, República del Ecuador. En la ciudad de Guayaquil – Ecuador y que en lo adelante se denominará como.
        /// </summary>
        internal static string Ctrt1TextoDos {
            get {
                return ResourceManager.GetString("Ctrt1TextoDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a representado en este acto por, {0}.
        /// </summary>
        internal static string Ctrt1TextoOcho {
            get {
                return ResourceManager.GetString("Ctrt1TextoOcho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}, con domicilio legal en: {1} en la Ciudad de {2} cuyos números telefónicos son: {3} y correo electrónico es: {4}; Que en lo sucesivo se denominará.
        /// </summary>
        internal static string Ctrt1TextoSeis {
            get {
                return ResourceManager.GetString("Ctrt1TextoSeis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a un Servicio de Facturación Electrónica en línea denominado INVOICEC, usando como plataforma la dirección electrónica:.
        /// </summary>
        internal static string Ctrt2TextoCuatro {
            get {
                return ResourceManager.GetString("Ctrt2TextoCuatro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a emitir los {0} documentos digitales según la nueva reforma tributaria ecuatoriana que son:.
        /// </summary>
        internal static string Ctrt2TextoSeis {
            get {
                return ResourceManager.GetString("Ctrt2TextoSeis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a podrá usar los recursos de INVOICEC y validar sus {0} documentos digitales con el SRI gracias a la comunicación entre el servidor.
        /// </summary>
        internal static string Ctrt4TextoDos {
            get {
                return ResourceManager.GetString("Ctrt4TextoDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a y se mantendrá en dicho servidor por un periodo de 1 años, además cada año fiscal se le facilitará los documentos digitales en formato XML. .
        /// </summary>
        internal static string Ctrt5TextoSiete {
            get {
                return ResourceManager.GetString("Ctrt5TextoSiete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a no se hace responsable por fallos provenientes del servidor del SRI, en este caso el SRI ha creado un plan de contingencia que permitirá validar los documentos. .
        /// </summary>
        internal static string Ctrt6TextoDos {
            get {
                return ResourceManager.GetString("Ctrt6TextoDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hará su mayor esfuerzo para la reserva, protección y confidencialidad de aquellos datos suministrados en el sistema ubicado en la dirección electrónica.
        /// </summary>
        internal static string Ctrt8TextoDos {
            get {
                return ResourceManager.GetString("Ctrt8TextoDos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a varios planes a su elección en base al precio y la cantidad de documentos electrónicos a procesar de forma anual. A continuación, se detalla el plan contratado entre .
        /// </summary>
        internal static string Ctrt9TextCuatro {
            get {
                return ResourceManager.GetString("Ctrt9TextCuatro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a emitir los {0} documentos digitales según la nueva reforma tributaria ecuatoriana que son:.
        /// </summary>
        internal static string CtrtCantidadDocumento {
            get {
                return ResourceManager.GetString("CtrtCantidadDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a De una parte: {0}.
        /// </summary>
        internal static string CtrtNombreEmpresa {
            get {
                return ResourceManager.GetString("CtrtNombreEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RUC {0}.
        /// </summary>
        internal static string CtrtRucEmpresa {
            get {
                return ResourceManager.GetString("CtrtRucEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONTRATO DE PRESENTACIÓN DE SERVICIOS DE FACTURACIÓN ELECTRÓNICA INVOICEC ENTRE SIPECOM Y EL SUBSCRITOR.
        /// </summary>
        internal static string CtrtTitulo {
            get {
                return ResourceManager.GetString("CtrtTitulo", resourceCulture);
            }
        }
    }
}
